### ISSUE TITLE
Compilation error on VS2019

### ISSUE THREAD

**Issue by edward9112** [ermig1979/Synet#13]
Error	C3861	'_mm_cvtsi64_si128': identifier not found

Reproduced in Release, Win32, VS2019 16.6.4

**Comment by ermig1979** [comment]
Thank you for bug report! The bug was reproduced. I will fix it as fast as possible.

**Comment by edward9112** [comment]
Awesome! Thank you!

> Thank you for bug report! The bug was reproduced. I will fix it as fast as possible.
