### ISSUE TITLE
Grayscale frames performance/accuracy

### ISSUE THREAD

**Issue by edward9112** [ermig1979/Synet#15]
Hello,

How do grayscale frames (instead of bgra) affect performance and detection accuracy of Synet algorithms?

Thank you

**Comment by ermig1979** [comment]
Hello! 

Synet only performs inference of trained network. If format of input image is differ from internal format of network Synet performs conversion of input image to required internal format. Ordinary the image conversion time is much lesser than inference of neural network. If you use grayscale image than color information is lost and it can lead to accuracy degradation (usually it is insignificant accurcy loss). 

To resize image to neural network input is better to use function Simd::Resize with parameter ::SimdResizeMethodArea.

**Comment by edward9112** [comment]
Thank you so much for the descriptive reply! Another question, is there any common recommendation for the optimal input image size? Or it all depends on the network and objects size?

**Comment by ermig1979** [comment]
There are neural models which support resizing. But most of them are trained for fixed input size. And of course the input size is determined by size of detected objects.

**Comment by edward9112** [comment]
Thank you very much for clearing that out.
I really admire your job with Simd, top class coding!
