### ISSUE TITLE
Quantization/INT8 support

### ISSUE THREAD

**Issue by SAN4EZ7714** [ermig1979/Synet#18]
Hello!

Is working with INT8 models currently supported?

In files perf.sh, test.sh, check.sh the quantization check is disabled, as well as test_003i and test_009i.
If I try to enable them manually, it start require file quant.xml, but it is missing from the project.

**Comment by ermig1979** [comment]
Hello!

Now I am developing my own quantization algorithm and testing it on my private models. I am going to add model quantization example soon.

**Comment by SAN4EZ7714** [comment]
I've seen new commits about quantization.
How about a small example?
