### ISSUE TITLE
Question about fp32/int8

### ISSUE THREAD

**Issue by teor292** [ermig1979/Synet#21]
Hi. We run converted from OpenVino framework 'face-detection-retail-0005' network and get next inference results on aarch64:

For fp32: 243,4ms
For int8: 856ms.

It is strange that for int8 the calculation is slower. Is that how it should be?

**Comment by ermig1979** [comment]
Unfortunately INT8 multiply and add operations is not good implemented on ARM platform. So it is a feature but not a bug.

**Comment by teor292** [comment]
Ok, thanks.
