### ISSUE TITLE
Tracker suggestion

### ISSUE THREAD

**Issue by edward9112** [ermig1979/Synet#23]
Hello Igor!

Can you suggest what kind of tracker is best to use with your detector?

Or maybe there is some kind of generic tracker incorporated with SIMD library?

Thank you!

**Comment by ermig1979** [comment]
There is a part of correlation tracker in Simd (see ShiftDetector).

**Comment by edward9112** [comment]
> There is a part of correlation tracker in Simd (see ShiftDetector).

Alright! Much appreciated!
