### ISSUE TITLE
Unsupported version 11 of IE model

### ISSUE THREAD

**Issue by edward9112** [ermig1979/Synet#26]
Hello,

I am trying to convert the latest Face detection model and getting this error:
`Unsupported version 11 of IE model
`
The model is here:
https://storage.openvinotoolkit.org/repositories/open_model_zoo/2022.1/models_bin/3/face-detection-0200/FP32/

**Comment by ermig1979** [comment]
Thank you for bug report! I will add support of  IE 11 in the nearest future.

**Comment by edward9112** [comment]
Awesome! It almost works!
On this model it shows another error:
`Not implemented layer : name = Subtract_302 ; type = Subtract ; id = 2`

https://storage.openvinotoolkit.org/repositories/open_model_zoo/2022.1/models_bin/3/vehicle-attributes-recognition-barrier-0042/FP32/

**Comment by edward9112** [comment]
Also, there is assert error:
```
File: C:\XXX\src\Synet\Layers\MetaLayer.h
Line: 401

Expression: src[i]->Count() == 1
```
On this model: https://storage.openvinotoolkit.org/repositories/open_model_zoo/2022.1/models_bin/3/age-gender-recognition-retail-0013/FP32/

**Comment by ermig1979** [comment]
Fixed bug in [vehicle-attributes-recognition-barrier-0042] (https://storage.openvinotoolkit.org/repositories/open_model_zoo/2022.1/models_bin/3/vehicle-attributes-recognition-barrier-0042/FP32/) model conversion. See test_018f.

**Comment by edward9112** [comment]
It works, thank you!
