### ISSUE TITLE
Onnx conversion issue

### ISSUE THREAD

**Issue by Pabur96** [ermig1979/Synet#28]
I try to convert my own custom onnx model but I get an error. 

Convert network from Onnx to Synet : Can't found layer onnx !
Can't found layer onnx !
Can't found layer onnx !
Can't found layer onnx !
Can't convert node[4]: type: Slice, name: Slice_4 ( images onnx::Slice_127 onnx::Slice_128 onnx::Slice_126 onnx::Slice_129 ) -> ( onnx::Slice_130 ) { } !

 Conversion finished with errors!
Do you have any idea why I get this error and maybe how I could fix it?

**Comment by ermig1979** [comment]
Hi! I need to get access to this model to fix the bug.

**Comment by ermig1979** [comment]
I fixed bugs. The conversion of the model works now. The conversion to NCHW format works without additional parameters. The conversion to NHWC format (which is faster then NCHW)   requires additional parameters (see attach).

I have some additional questions:
1) Can I add this model to public test?
2) If the first answer is positive then what this model do and how to test it.

[param.zip](https://github.com/ermig1979/Synet/files/8669017/param.zip)

**Comment by Pabur96** [comment]
@ermig1979 Thank you very much. 
I would prefer to not make it public, because it belongs to my company.
I can only tell you that it's my custom yolov5s model converted to onnx.
