### ISSUE TITLE
test_onnx can't recognize "convert" mode

### ISSUE THREAD

**Issue by trlsmax** [ermig1979/Synet#35]
I try to compile Synet on win10, and test_onnx can't recognize convert mode;
```
E:\projects\synet\bin\v143\x64\Release>.\TestOnnx.exe -m convert -fw best.onnx -sm best.xml -sw best.bin
[000] Error: Unknown mode :
```

**Comment by ermig1979** [comment]
Hi. 
At present conversion of ONNX models to Synet format works only for Linux. 
But model inference forks for Windows and Linux both.
Possible in future I will add the possibility of ONNX model conversion for Window.

**Comment by trlsmax** [comment]
Thank you for your reply. I will try it on Linux.
