### ISSUE TITLE
TestOnnx Win32 throws 0xC0000005 exception

### ISSUE THREAD

**Issue by theoractice** [ermig1979/Synet#39]
Testing on Win10 x64 system.

I could not build latest code, So I used Simd v6.1.139 and commit c9958738a3e65e7f2f55d89ca68bc7d7658ee6de (the one just before Simd v6.1.139 was released).

x64 binary worked like a charm (I had already converted `other.onnx` to Synet format under Linux).
```
⠕ TestOnnx.exe -m=compare
Start  and Synet(fp32) single-thread comparison tests :
Tests are finished successfully!

Synet(fp32) memory usage: 31.4 MB.
----- Performance Report -----
Simd Library: 6.1.139; CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz; System Sockets: 1, Cores: 6, Threads: 12; Cache L1D: 32 KB, L2: 256 KB, L3: 12288 KB, RAM: 32605 MB; Available SIMD: AVX2 FMA AVX SSE4.1 SSSE3 SSE3 SSE2 SSE
Test::SynetNetwork::Init{ fp32 }: 21 ms / 1 = 20.598 ms {min = 20.598; max = 20.598}
Test::SynetNetwork::Predict{ fp32 }: 110 ms / 10 = 10.971 ms {min = 10.732; max = 11.125} 72.8 GFlops
```

But Win32 binary gave me a `0xC0000005` exception here:
![image](https://github.com/user-attachments/assets/9a58c597-ac9c-4894-a37a-5db7c19b5706)

**Comment by ermig1979** [comment]
Hi! Excuse me for so late answer - I was at vacation. I try to reproduce this bug but TestOnnx works fine in Win32 mode. So I need more information to reproduce and fix this bug.

**Comment by theoractice** [comment]
Thanks for your kind reply. Here are the steps to reproduce the issue:

- Install VS2022 latest version on a Win10 x64 system.
- `git clone` the Synet repo, then revert to commit https://github.com/ermig1979/Synet/commit/c9958738a3e65e7f2f55d89ca68bc7d7658ee6de.
- Download Simd v6.1.139 and unzip to `Synet\3rd` folder. I did the above because the latest Synet VS2022 solution just won't compile.
- Insert one line: `#include "Simd/SimdConfig.h"` to `TestOnnx.cpp` before line 28: `#include "TestCompare.h"`. I did this because `TestOnnx` was configured to `/MT` by default and it won't compile without `SIMD_STATIC` defined.
- Copy the model files to `Synet\prj\vs2022` in order to let VS2022 find them when debugging. The Synet model files are converted from onnx model files under `Synet\data\onnx\test_001` and has been tested to work with `TestOnnx` x64 binary under linux x64 and Win10 x64 respectively. The model files are uploaded here just in case: 
[Synet.zip](https://github.com/user-attachments/files/16707297/Synet.zip)

- Compile `TestOnnx` with `Release/Win32` mode and run.

Files under `Synet\data\onnx\test_000` failed to load, either. I can see that those model files hasn't been changed for a while, so I have no idea.

**Comment by ermig1979** [comment]
I compiled TestOnnx on Release/Win32 with static Simd. And it works fine.

**Comment by theoractice** [comment]
> Is this critical - to fix bug in that specific commit?

Of course not. I was just trying to repeat exactly what I did when I encountered the bug.
Now I have updated to the latest source code and everything is fine. Guess I was running out of luck then.
Issue closed.
