### ISSUE TITLE
Are you going to implement some fast conv algorithm like winograd,fft?

### ISSUE THREAD

**Issue by szad670401** [ermig1979/Synet#4]
the im2col + gemm maybe a little slow.

**Comment by ermig1979** [comment]
Hello. I have plans to make the inference of convolution layer so fast as possible. So I will try to implement these methods when I finish current tasks connected with compatibility Synet and Caffe and Tensorflow models.

**Comment by szad670401** [comment]
thank you.
I found the opencv dnn have implemented the tensorflow importer. you can refer to its desgin. but the dnn module can't compute with low precison , therefore it run a little bit slow on ARM. I very look forward you will work on low precision computing.

**Comment by ermig1979** [comment]
I have seen this importer. It was useful in order to understand inner structure of Tensorflow. Unfortunately it is not enough in order to convert complicated models.

**Comment by szad670401** [comment]
yes. tensorflow has two much ops. some chinese company open source some mobile tiny CNN inference framework.
reference:
1.[Mace](https://github.com/XiaoMi/mace)
2.[NCNN](https://github.com/Tencent/ncnn)
3.[FeatherCNN](https://github.com/Tencent/FeatherCNN)

**Comment by ermig1979** [comment]
Thank you for information. And I want to note that I have implemented Winograd 3x3 2x2 convolutions. It gives performance improvement in some cases.

**Comment by szad670401** [comment]
A great work.
I have seen you have implemented most of common layer. 
Have you planed to give out some benchmark tests that comparing with other frameworks?

**Comment by ermig1979** [comment]
I I periodically do performance comparison between Synet and (Darknet/Caffe/Tensorflow/Opencv:Dnn).  Synet contains tests which compare Synet and Darknet. Other comparison tests are not ready to publication. I will try to do they. 
Now I am experementing with image format. In some cases NHWC is faster then NCHW.

**Comment by ermig1979** [comment]
Winograd's algorithms with kernel 3x3 and window 2x2, 3x3, 4x4 were implemented.
