### ISSUE TITLE
Assert failed on model load

### ISSUE THREAD

**Issue by edward9112** [ermig1979/Synet#41]
Hi, Igor!

I am getting the assertion error while trying to Network.Load() the following model:

[person-vehicle-bike-detection-2000
](https://storage.openvinotoolkit.org/repositories/open_model_zoo/2023.0/models_bin/1/person-vehicle-bike-detection-2000/FP32/)

```
assert(_type != TensorTypeUnknown && _type == GetTensorType<U>());
>	UseSample.exe!Synet::Tensor<float>::Resize<int>(int value) Line 519	C++
```

```
UseSample.exe!Synet::Tensor<float>::Resize<int>(int value) Line 519
	at C:\Synet\src\Synet\Tensor.h(519)
```

**Comment by edward9112** [comment]
Hello,

Any updates on how to fix it?

**Comment by ermig1979** [comment]
Hello! The bug was fixed. Thank you for bug report!

**Comment by edward9112** [comment]
Wow! Thank you so much!
