### ISSUE TITLE
Can't load network. MSVC compiler bug?

### ISSUE THREAD

**Issue by teor292** [ermig1979/Synet#8]
Hi. There is a problem: On visual studio 2019 and 2015 (32 bit, not tested on others, 64 bit works) it is impossible to convert and load synet network. Here is screenshot of converting error:

![bug](https://user-images.githubusercontent.com/24866664/69437792-9a8f9c80-0d4c-11ea-8e25-3d9c36d321b1.png)

The error while trying load is similar.

In memory windows there is something strange: the pointer to virtual table begins with 4 byte offset. But after that there is a trash, and only after - there is a first "params" data. So, I think it is the compiler bug, but not sure. On gcc everything works fine. Can you test your framework on visual studio to investigate this bug?

**Comment by ermig1979** [comment]
Thank you for bug report. I will try to reproduce this bug next week beginning.

**Comment by SmallDonkey** [comment]
And Visual Studio 2017 has such a problem?

**Comment by ermig1979** [comment]
The bug was fixed.

P.S. I rarely use 32-bit mode so it is not tested enough.
