### ISSUE TITLE
Ошибка при конвертировании text-detection-0002.bin/text-detection-0002.xml 

### ISSUE THREAD

**Issue by SmallDonkey** [ermig1979/Synet#9]
Ошибка при конвертировании text-detection-0002.bin/text-detection-0002.xml 

**_Cant't convert layer :  type = Interp, name = pixel_cls/resize_images/ResizeBilinear, id = 122 !_**

VS 2019 x64 Debug

face_detection конвертируется нормально

**Comment by ermig1979** [comment]
Thank you for bug report! The error was fixed!
